apiVersion: v1
kind: Pod
metadata:
  name: nginx-banana
  labels:
    app: banana
spec:
  initContainers:
  - name: init-container
    image: busybox
    command: ["sh", "-c", "echo I am Banana > /usr/share/nginx/html/index.html"]
    volumeMounts:
    - name: html-volume
      mountPath: /usr/share/nginx/html
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: html-volume
      mountPath: /usr/share/nginx/html
    imagePullPolicy: IfNotPresent
  volumes:
  - name: html-volume
    emptyDir: {}